name: app_base
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  google_fonts: ^6.2.1
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^10.0.0
  win32: ^5.7.1
  carousel_slider: ^5.0.0
  flutter_lucide: ^1.4.0
  lucide_icons: ^0.257.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
  - family: DancingScript
    fonts:
      - asset: assets/fonts/static/DancingScript-Regular.ttf

  uses-material-design: true

  assets:
    - assets/images/fundo.png
    - assets/images/papa.png
    - assets/animations/alimentos.json
    - assets/animations/mulherPensando.json
    
flutter_icons:
  android: true
  image_path: assets/icon/icon.png
